
export type Animal = {
  slug: string;
  name: string;
  category: 'Mammals' | 'Birds' | 'Reptiles' | 'Marine Life';
  commonName: string;
  description: string;
  imageUrl: string;
  bannerUrl: string;
  overview: string;
  habitat: string;
  diet: string;
  behavior: string;
  status: {
    lifespan: string;
    weight: string;
    conservation: string;
  };
  relatedSpecies: string[];
  videoUrl?: string;
};

export const animals: Animal[] = [
  {
    slug: 'african-elephant',
    name: 'Loxodonta africana',
    category: 'Mammals',
    commonName: 'African Elephant',
    description: 'The largest land animal, known for its intelligence and complex social structure.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'African elephants are the largest land animals on Earth. They are slightly larger than their Asian cousins and can be identified by their larger ears that are shaped somewhat like the continent of Africa.',
    habitat: 'Found in a variety of habitats including savannas, forests, and marshlands across Africa.',
    diet: 'Elephants are herbivores, spending much of their day eating. Their diet consists of grasses, leaves, bark, fruit, and a variety of foliage.',
    behavior: 'They live in complex social structures led by a matriarch. Elephants are known for their high intelligence, long memory, and deep family bonds. They communicate using a wide variety of sounds.',
    status: {
      lifespan: '60-70 years',
      weight: 'Up to 6,000 kg (13,000 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['rhinoceros', 'giraffe'],
    videoUrl: 'https://www.youtube.com/embed/nS_3Uv_2A7c',
  },
  {
    slug: 'siberian-tiger',
    name: 'Panthera tigris tigris',
    category: 'Mammals',
    commonName: 'Siberian Tiger',
    description: 'The world\'s largest cat, a powerful predator of the Russian Far East.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The Siberian tiger, also known as the Amur tiger, is a tiger population of the subspecies Panthera tigris tigris native to the Russian Far East and Northeast China. It is the largest of all wild cats.',
    habitat: 'They live primarily in the birch forests of Russia\'s Far East, though some exist in China and North Korea.',
    diet: 'Siberian tigers are carnivores, preying on animals like wild boar, red deer, moose, and roe deer. They are powerful hunters capable of taking down large prey.',
    behavior: 'Tigers are solitary hunters, using their distinctive striped coat as camouflage. They are territorial and mark their large home ranges with urine and scratches.',
    status: {
      lifespan: '10-15 years in the wild, up to 20 in captivity',
      weight: 'Up to 300 kg (660 lbs)',
      conservation: 'Endangered',
    },
    relatedSpecies: ['lion'],
  },
   {
    slug: 'red-panda',
    name: 'Ailurus fulgens',
    category: 'Mammals',
    commonName: 'Red Panda',
    description: 'A small mammal native to the eastern Himalayas and southwestern China.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The red panda, with its reddish-brown fur, long, shaggy tail, and waddling gait, is a solitary animal, mainly active from dusk to dawn. Despite its name, it is not closely related to the giant panda.',
    habitat: 'Temperate forests with bamboo understories in the Himalayas.',
    diet: 'Primarily eats bamboo, but also eggs, birds, and insects.',
    behavior: 'Arboreal, skillful and acrobatic climbers that spend most of their time in trees.',
    status: {
      lifespan: '8-10 years',
      weight: '3-6 kg (7-14 lbs)',
      conservation: 'Endangered',
    },
    relatedSpecies: ['giant-panda'],
  },
  {
    slug: 'giant-panda',
    name: 'Ailuropoda melanoleuca',
    category: 'Mammals',
    commonName: 'Giant Panda',
    description: 'A bear native to south-central China, known for its iconic black-and-white coat.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The giant panda is a beloved bear species recognized by its distinct black-and-white coloring. Despite being classified as a carnivore, its diet is over 99% bamboo.',
    habitat: 'Mountainous regions of central China, primarily in Sichuan, but also in neighboring Shaanxi and Gansu provinces.',
    diet: 'Almost entirely bamboo. They must eat 26 to 84 pounds of it every day, depending on what part of the bamboo they are eating.',
    behavior: 'Giant pandas are generally solitary. They have a highly developed sense of smell that males use to avoid each other and to find females for mating in the spring.',
    status: {
      lifespan: 'About 20 years in the wild',
      weight: 'Up to 125 kg (275 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['red-panda'],
  },
  {
    slug: 'lion',
    name: 'Panthera leo',
    category: 'Mammals',
    commonName: 'Lion',
    description: 'The "king of the jungle," a social big cat living in prides, known for its powerful roar and majestic mane.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The African lion is often called the "king of the jungle," although it primarily inhabits savannahs and grasslands. Male lions are unique among big cats for their impressive manes, which grow darker and fuller with age. Lions are the second-largest big cats after tigers and live in social groups called prides. Both males and females can produce a thunderous roar audible up to 8 km away, a sound that asserts territory and helps pride members find one another. These apex predators symbolize strength and have been revered in human culture for millennia.',
    habitat: 'Lions once roamed across Africa, Asia, and Europe, but today they survive mainly in sub-Saharan Africa (with a small population of Asiatic lions in India). They prefer grassy plains, savannahs, open woodlands, and scrub, where sufficient prey is available. Shade from scattered trees or thickets offers relief from midday heat.',
    diet: 'Obligate carnivores, lions primarily hunt large herbivores such as zebras, wildebeest, buffalo, and antelope. Working in groups, a pride’s lionesses cooperate to stalk and ambush prey. A lion can consume up to 30% of its body weight in a single meal. They are also opportunistic scavengers—often driving off smaller predators (like hyenas or wild dogs) to steal carcasses.',
    behavior: 'Lions are the most social of the big cats, living in prides that usually consist of related females, their cubs, and one or a few adult males. Females do most of the hunting, using teamwork to bring down prey. Male lions, with their larger size and mane, often take on protective roles, defending the pride’s territory (which can span over 250 km²) against rival males. Territorial behavior includes roaring choruses and scent-marking with urine. Despite their fearsome reputation, lions spend a lot of their time resting – up to 20 hours a day conserving energy for hunting bouts. When active, they are generally nocturnal or crepuscular (dawn/dusk) hunters, avoiding the heat of day. When active, they are generally nocturnal or crepuscular (dawn/dusk) hunters, avoiding the heat of day.',
    status: {
      lifespan: '10-14 years in the wild',
      weight: '120-200 kg (265-440 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['siberian-tiger', 'cheetah', 'jaguar'],
  },
  {
    slug: 'cheetah',
    name: 'Acinonyx jubatus',
    category: 'Mammals',
    commonName: 'Cheetah',
    description: 'The world’s fastest land animal, renowned for its speed and grace.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The cheetah is the world’s fastest land animal, renowned for its speed and grace. It has a lean build with long legs, a flexible spine, and semi-retractable claws – all adaptations for running down prey in bursts of astonishing acceleration. A cheetah can sprint from 0 to 95 km/h in mere seconds and reach top speeds around 100–120 km/h (about 60–75 mph), although only for short distances (~500 m). Its coat is tan with black spots, providing camouflage in the grasslands. Unlike other big cats, cheetahs do not roar; they purr and chirp, and they are relatively lightly built, built for speed over strength.',
    habitat: 'Cheetahs favor open savannahs, grasslands, and arid deserts where they can make full use of their speed in open terrain. Historically ranging throughout Africa, the Middle East, and into India, they are now mostly found in sub-Saharan Africa with a small critically endangered population in Iran. They thrive in areas with good visibility and plentiful prey, such as expansive plains or lightly wooded bushveld.',
    diet: 'A carnivore that relies on speed, the cheetah primarily hunts medium-sized ungulates. Common prey include impalas, gazelles (like Thomson’s gazelle), springbok, young wildebeest, and hares. Cheetahs are diurnal hunters (active mainly in early morning or late afternoon) to avoid competition with stronger nocturnal predators. They use a stealthy stalk to get within sprinting distance, then explode in a chase. A successful cheetah will often trip its prey with a swipe of the paw and suffocate it with a bite to the throat. Cheetahs eat quickly to avoid losing their kill – they’re frequently displaced by lions, hyenas, or leopards, being less powerful fighters.',
    behavior: 'Unlike lions, cheetahs are solitary or live in small family groups. Adult females are solitary except when raising cubs. Males may form small coalitions (often littermates) that stay together for life, cooperating to defend a territory and hunt. Cheetahs do not have the strength to fight larger carnivores and often surrender kills to them. They avoid confrontation and rely on their incredible acceleration and agility to survive. Cheetah cubs have a mantle of long, silvery fur on their backs, thought to mimic the appearance of a honey badger (possibly to deter some predators). Mothers raise cubs alone, moving them frequently and teaching them hunting skills.',
    status: {
      lifespan: '~10–12 years',
      weight: '~35–60 kg',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['lion', 'jaguar'],
  },
  {
    slug: 'jaguar',
    name: 'Panthera onca',
    category: 'Mammals',
    commonName: 'Jaguar',
    description: 'The largest cat of the Americas and third-largest in the world, a powerful predator of dense rainforests.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The jaguar is the largest cat of the Americas and third-largest in the world (after the tiger and lion). Stocky and immensely powerful, jaguars have muscular limbs and a broad head with a strong jaw. They boast the strongest bite force relative to size of any big cat – strong enough to crack turtle shells. Their beautiful coat is golden-yellow with black rosettes (spots with central dots) and solid black spots on limbs and head. Melanistic jaguars (all-black) are sometimes called “black panthers.” Jaguars are elusive and largely solitary, often linked with the dense tropical rainforests of the Amazon and Pantanal, but they also range in scrub, swamps, and even arid grasslands. They are exceptional swimmers and climbers, comfortable in and around water.',
    habitat: 'Jaguars historically ranged from the southwestern United States through Mexico and Central America into South America as far as northern Argentina. Today they are found mostly in the Amazon Basin, Pantanal wetlands, the Gran Chaco, and parts of Central America and Mexico (extirpated from most of the US). They inhabit tropical rainforests, flooded wetlands, dry scrub, and woodland – adaptable to various environments as long as there is dense cover and water. They often favor habitats near rivers and marshes, reflecting their propensity for swimming and hunting aquatic prey.',
    diet: 'Jaguars are apex predators with a broad diet. They are opportunistic hunters, preying on over 85 species. Common prey includes capybaras, peccaries, deer, tapirs, monkeys, birds, reptiles, and fish. Uniquely, jaguars often kill by delivering a crushing bite directly to the skull of prey, piercing the brain – a technique effective for reptiles like turtles and caimans, whose shells or thick hides are no match for the jaguar’s bite. In fact, jaguars have been observed biting through turtle and tortoise shells. They also ambush livestock in some areas, which can lead to conflict with humans. Jaguars typically drag kills to secluded spots or even up trees (though their tree-climbing is less practiced than leopards’) to eat in peace.',
    behavior: 'Jaguars are solitary and mainly nocturnal or crepuscular. Males maintain large territories that may overlap with those of several females, but they aggressively keep other adult males out. They communicate via scent marking (scrapes and urine) and deep, hoarse vocalizations (called saw-like roars). Excellent swimmers, jaguars readily enter water to catch fish, turtles, or caimans. They can be stealthy ambushers on land or lie in wait at riverbanks for prey coming to drink. Mothers give birth to 1–4 cubs and raise them without the male’s help. Cubs stay up to two years, learning to hunt before dispersing. Though formidable, jaguars yield to larger predators (like crocodilians) occasionally and avoid humans. They are a keystone species, crucial for controlling prey populations and maintaining ecosystem balance.',
    status: {
      lifespan: '12–15 years',
      weight: '70–100 kg',
      conservation: 'Near Threatened',
    },
    relatedSpecies: ['siberian-tiger', 'cheetah', 'lion'],
  },
  {
    slug: 'leopard',
    name: 'Panthera pardus',
    category: 'Mammals',
    commonName: 'Leopard',
    description: 'A versatile and stealthy big cat found in Africa and Asia, renowned for its climbing ability.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The leopard is a versatile and stealthy big cat found in Africa and parts of Asia. It has a lean, muscular body with short powerful limbs and a long tail that aids in balance. Its coat is tawny golden with black rosettes (no central dot) on the body and solid black spots on the face and limbs. This pattern provides excellent camouflage in a variety of environments, from grasslands to forests. Leopards are renowned for their strength-to-weight ratio and arboreal prowess – they can haul prey larger than themselves into trees, an ability that protects their kills from scavengers. Smaller than lions and tigers, but with a broad geographic range and adaptable behavior, the leopard is the most widespread big cat.',
    habitat: 'Leopards occupy a wide range of habitats – savannas, woodlands, equatorial forests, mountain highlands, semi-deserts, and even urban fringes. In Africa, they thrive in savannahs and open woodlands, as well as equatorial rainforests. In Asia, they range from tropical forests in India and Southeast Asia to temperate forests and rugged mountains (as in the Caucasus). They are at home both in hot lowlands and cool highlands. This adaptability is aided by their solitary and elusive nature. Leopards often rest in trees or dense thickets during the day and patrol large territories at night.',
    diet: 'Supremely opportunistic, leopards eat anything from insects and rodents to hoofed animals several times their weight. Common prey are medium-sized antelope (impala, bushbuck), deer, warthogs, monkeys, and in Asia, animals like chital or wild boar. They will also catch birds, reptiles, hares, and even fish if available. In settlements, they may prey on dogs or livestock (leading to conflict). A hallmark of leopard behavior is dragging kills into trees: a leopard can carry prey up to three times its own weight into a tree’s branches, securing the meal from hyenas or lions on the ground. They stash carcasses on high limbs and return to feed over several days. This tree-caching ability allows leopards to coexist in areas with larger carnivores by avoiding direct confrontation.',
    behavior: 'Leopards are solitary, coming together only to mate or for a mother to rear cubs. They are primarily nocturnal, using darkness to stalk and ambush. Exceptionally stealthy, a leopard moves silently and often very close to the ground when approaching prey. Leopards mark territory with claw scratches on trees and urine sprays. Males’ territories overlap those of several females, and males may fight fiercely over mating rights. Females give birth to litters of 1–3 cubs in a hidden den (rock crevice, thicket, or hollow tree). She frequently moves the cubs to new safe locations and teaches them hunting skills until they disperse around 18–24 months old. In conflict with other predators, leopards avoid direct fights – they often quietly yield kills to aggressive scavengers, or slink away from lions. Thanks to their climbing skill and adaptability, they manage to survive in proximity to more dominant species and even on human outskirts (feeding on rodents or domestic animals). They are powerful swimmers as well, though they don’t take to water as readily as jaguars.',
    status: {
      lifespan: '12–17 years',
      weight: 'males ~50-90 kg, females ~30-60 kg',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['lion', 'siberian-tiger', 'jaguar', 'cheetah'],
  },
  {
    slug: 'gray-wolf',
    name: 'Canis lupus',
    category: 'Mammals',
    commonName: 'Gray Wolf',
    description: 'A highly social canine known for its evocative howl and pack behavior.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The gray wolf is a highly social canine known for its evocative howl and pack behavior. Wolves have a lean, powerful build with long legs and thick fur, which can vary in color from white to gray, brown, or black. They are the largest wild members of the dog family. A wolf’s penetrating eyes, keen senses, and endurance make it a top predator of its range. Wolves are famous for their packs – family units that coordinate to hunt and raise offspring. Their howling chorus at night serves as bonding within the pack and as a territorial call that can carry for several miles.',
    habitat: 'Wolves once ranged across much of the Northern Hemisphere. They thrive in diverse habitats: forests (boreal, temperate, tropical), tundra, grasslands, mountains, and even deserts. Key habitat needs are adequate prey and room to roam. In North America, they are found from the Arctic tundra and boreal forests of Canada and Alaska to the temperate Rockies and the forests of the Great Lakes region. In Eurasia, wolves inhabit areas from the European woodlands and alpine zones to Siberian taiga and Asian steppes. They can traverse long distances – wolf territories can cover anywhere from 100 to over 2,000 km² depending on prey density.',
    diet: 'Wolves are carnivores that primarily hunt ungulates. Common prey include deer, elk, moose, caribou, and wild boar, as well as smaller mammals like beavers or hares when large prey is scarce. Pack cooperation allows wolves to take down animals much larger than an individual wolf. A hunting pack may trot tirelessly for hours to find prey, then test herds to single out vulnerable individuals (young, old, or weak). They use stamina to chase and teamwork to corner prey, delivering bites to the hindquarters to slow it and a bite to the throat or snout to finish the kill. Wolves will also scavenge carrion and have been known to eat berries or fish opportunistically. In lean times, they can go without food for over a week, then gorge 10–20 kg in one meal when a kill is made.',
    behavior: 'Pack structure is the cornerstone of wolf life. A typical pack is an extended family led by an alpha pair (dominant breeding male and female) and includes their offspring of one or more years. Pack size can range from 2–3 up to 10 or more, depending on family success. The alpha pair are usually the only breeders, and they maintain order through posture, eye contact, and subtle cues rather than constant violence. Younger wolves have a defined hierarchy (beta, omega, etc.), and each pack member has roles in hunting and pup-rearing. Wolves communicate through a range of vocalizations (howls, barks, whines), body language (tail position, ear angle, stance), and scent marking. Howling is perhaps their best-known call – a lone wolf’s howl may be answered by pack mates in a group chorus that can be heard up to 10 km away on open terrain. Howling serves to assemble the pack and warn neighboring packs of occupancy.',
    status: {
      lifespan: '6-8 years in the wild',
      weight: '30-50 kg',
      conservation: 'Least Concern',
    },
    relatedSpecies: [],
  },
  {
    slug: 'mountain-gorilla',
    name: 'Gorilla beringei beringei',
    category: 'Mammals',
    commonName: 'Mountain Gorilla',
    description: 'One of two subspecies of eastern gorilla, famed for its majestic presence in the cloud forests of Central Africa.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The mountain gorilla is one of two subspecies of eastern gorilla, famed for its majestic presence in the cloud forests of Central Africa. It is among our closest relatives, sharing roughly 98% of its DNA with humans. Mountain gorillas have a thick, shaggy coat (providing insulation in cool high-altitude habitats), with adults displaying a notable sexual dimorphism: males are much larger and develop a patch of silver hair on their back (hence “silverback”) when mature. They possess immense strength – an adult male can weigh 150–200 kg and has the physical power to bend branches or tear vines with ease, yet gorillas are generally gentle giants, feeding primarily on vegetation. Their social groups are tightly knit and often peaceful, led by a dominant silverback male.',
    habitat: 'Mountain gorillas live in montane and subalpine forests at elevations of about 2,200–4,300 m (7,000–14,000 ft). They are found only in two isolated populations: the Virunga volcanic range (straddling Rwanda, Uganda, and the Democratic Republic of Congo) and the Bwindi Impenetrable National Park in Uganda. These forests are cool, misty, and lush.',
    diet: 'Primarily herbivorous, mountain gorillas have a vegetarian menu consisting of leaves, stems, shoots, and roots of many plant species. A smaller portion of their diet is fruits (when in season). They also occasionally ingest ants, snails or grubs incidentally while eating foliage.',
    behavior: 'Mountain gorillas are highly social, living in stable troops averaging about 5 to 20 individuals. The silverback leads the group, making decisions on movement, feeding, and resting, and will defend the troop against threats. Communication includes a variety of vocalizations: content grunts and belches, screams or roars when alarmed, and the iconic chest beat.',
    status: {
      lifespan: '35-40 years in the wild',
      weight: '140–195 kg (males), 90–120 kg (females)',
      conservation: 'Endangered',
    },
    relatedSpecies: [],
  },
  {
    slug: 'orangutan',
    name: 'Pongo spp.',
    category: 'Mammals',
    commonName: 'Orangutan',
    description: 'The only great ape native to Asia, famed for its bright orange-red hair and remarkable intelligence.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Orangutans are the only great apes native to Asia and are famed for their bright orange-red hair and remarkable intelligence. The name "orangutan" comes from Malay words "orang hutan," meaning "person of the forest", an apt description for these tree-dwelling apes. There are three species (Bornean, Sumatran, and the newly identified Tapanuli orangutan), all critically endangered. Orangutans have very long arms (up to 2 m span) and short legs, suited for brachiation – swinging through trees. A mature male develops cheek pads (flanges) and a throat pouch that helps produce loud “long calls.” These apes are highly intelligent: they use tools in the wild (e.g. using sticks to extract insects or seeds) and have sophisticated nesting and feeding behaviors. Orangutans are mostly solitary, a lifestyle shaped by their dispersed food resources, unlike the more social African apes.',
    habitat: 'Orangutans live in tropical rainforests on the Southeast Asian islands of Borneo and Sumatra. They are almost completely arboreal – spending over 90% of their time in the forest canopy. They favor old-growth forests with closed canopies and abundant fruiting trees. Orangutans are found from lowland swamp forests and peat swamps to upland forests up to ~1,500 m elevation. They build new sleeping nests high in the trees each night by bending and interweaving branches into a sturdy platform. The rich, fruit-heavy forests of Sumatra allow for somewhat higher densities and more social interactions than in Borneo, where food can be more sparse and orangutans more spread out.',
    diet: 'Orangutans are omnivorous, but fruit is the centerpiece of their diet. In season, ripe fruits (like figs, durians, mangoes) can comprise 60–90% of intake. They have an incredible ability to remember fruiting seasons and locations of trees across their home range. Besides fruit, orangutans eat young leaves, shoots, bark, and flowers. They will also consume insects (like ants and termites) and occasionally bird eggs or small vertebrates, though these are minor in their diet. When preferred fruits are scarce, they rely on tougher foods (bark, woody stems) and even soil rich in minerals for nutrition. Orangutans have been observed using tools to acquire food: for instance, using sticks to extract honey or to pry out seeds from spiky fruits. They drink water collected in tree hollows or from rain by cupping their hands or using leaves as makeshift cups. Their slow metabolism and energy-conserving lifestyle help them get by when fruit is not plentiful.',
    behavior: 'Orangutans are the least social of the great apes. Adult males are solitary, maintaining large overlapping home ranges that encompass those of several females. They generally come together only for mating. Adult females are usually accompanied only by their dependent offspring. The mother-infant bond in orangutans is one of the strongest in the animal kingdom: a baby orangutan clings to its mother’s body for the first year, nurses for 5–6 years, and stays with the mother learning survival skills for 7–8 (sometimes up to 9) years – the longest childhood of any non-human animal. This slow reproductive rate (a female gives birth only once every ~7–8 years) is a big factor in orangutan vulnerability.',
    status: {
      lifespan: '30-40 years in the wild',
      weight: 'Males ~75-100 kg, Females ~30-50 kg',
      conservation: 'Critically Endangered',
    },
    relatedSpecies: ['mountain-gorilla'],
  },
  {
    slug: 'chimpanzee',
    name: 'Pan troglodytes',
    category: 'Mammals',
    commonName: 'Chimpanzee',
    description: 'A highly intelligent great ape and one of humanity\'s closest living relatives.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The chimpanzee is one of humans’ closest living relatives, sharing approximately 98.8% of our DNA. These great apes are highly intelligent, social, and adaptable. They have coarse black hair (that greys with age), expressive faces, and opposable thumbs (and big toes) enabling them to skillfully grasp objects. Chimpanzees are known for making and using tools – a capability once thought to be uniquely human. For example, they fashion twigs to "fish" for termites, inserting the stick into a mound and licking off the insects. Dr. Jane Goodall’s groundbreaking observations in the 1960s (at Gombe, Tanzania) revealed such behaviors and forced science to “redefine tool, redefine Man, or accept chimpanzees as humans” as anthropologist Louis Leakey famously quipped. Chimps are strong (a male chimp is several times stronger than an adult human) and can be aggressive, but also show deep social bonds, affection, and even strategic thinking. They live in complex communities with male dominance hierarchies and dynamic relationships.',
    habitat: 'Chimpanzees reside in tropical forests and woodland-savanna mosaics of equatorial Africa. Their range spans across about 21 African countries, from west (Sénégal) through the Congo Basin to East Africa (western Tanzania, Uganda). They inhabit primary and secondary rainforests, montane forests up to ~2,800 m, swamp forests, and mixed woodland/grassland areas where fruit trees are interspersed. Chimps are both arboreal and terrestrial: by day they often climb and travel in the trees (especially when feeding), but also spend significant time on the ground, knuckle-walking. At night, they sleep in treetop nests for safety. They are adaptive and resourceful – in more open habitats, chimps may walk upright more often to see over tall grass or carry food, and seek shade under trees or caves in the heat.',
    diet: 'Chimpanzees are omnivorous, with a majority of their diet being plant-based. Fruit is the preferred food – figs, bananas, and myriad forest fruits make up a large portion of their intake. They also eat young leaves, blossoms, stems, seeds, and resin. Chimps will consume insects (such as termites and ants) by probing nests with sticks, delicately gathering them. Uniquely among primates, chimpanzees also hunt and eat meat: they have been observed hunting colobus monkeys, bushbabies, young bush pigs, or small antelopes (like duikers). These hunts are often cooperative – males may coordinate to flush and corner arboreal monkeys. Meat is not daily fare but can be an important protein source and is sometimes shared within the group (often as a political or bonding tool; e.g. a successful hunter might share meat to curry favor). Additionally, chimps eat bird eggs and honey when they can get them (using chewed leaf sponges to extract honey from tree cavities). They also ingest soil or clay in small amounts, possibly for minerals or detoxification of some seeds. This broad diet showcases their adaptability to seasonal changes in food availability.',
    behavior: 'Chimpanzees live in multi-male, multi-female communities (called troops or "communities") that can number from 15 up to 100 individuals, but they usually split into smaller subgroups (parties) that change composition frequently – a social structure known as fission-fusion. At the core are females and their young, while males remain in their birth community and form the political backbone. Within a community, males have a dominance hierarchy and there is usually an alpha male who leads. The alpha male may display spectacular charging behaviors – running, hooting, dragging branches, and flailing – to intimidate rivals and impress others. Females have their own hierarchy but are generally less overtly aggressive. Chimps are highly social and communicative. They greet friends with embraces, touches, or by grooming each other. Grooming is a vital social activity; it not only removes parasites but also builds alliances and soothes tensions. Vocalizations range from pant-hoots (a rising whoop that can crescendo and is used to announce presence or excitement), to screams (during fights or panic), to quieter grunts and lipsmacks during feeding. When on the move through the forest, they keep contact with soft “hoo” calls. If excited or during hunting, they may drum on tree buttresses with their hands, producing a loud booming. Young chimps engage in a lot of play – wrestling, tickling, and chasing – which helps them develop coordination and social skills. A hallmark of chimp behavior is tool use and problem-solving. Different populations have unique “cultures”: for instance, some use sticks to fish for termites, others use stone hammers and anvils to crack nuts (seen in West Africa), and some use leaves as sponges to soak up drinking water. Chimps also demonstrate planning; a male might quietly position himself for a surprise ambush on rivals, or prepare a handful of rocks to throw during a dominance display. They have been observed using sharp sticks to hunt small mammals in some areas – an example of primate proto-tool-use for hunting. Chimp society can be violent at times. Males sometimes form coalitions to rise in rank or depose an alpha. Rival communities may engage in lethal border conflicts – male gangs patrolling the edges of their territory will attack outsiders, sometimes killing individuals from neighboring groups (this can resemble primitive warfare). Infanticide (killing infants of rival males or new females) occurs in certain contexts. Despite this, chimp life also involves deep bonds: mothers and offspring share a tight connection (young chimps ride clinging to mom’s belly and later her back). Orphaned juveniles have been “adopted” by older siblings or even unrelated adults in some cases. At night, each chimp makes a nest in a tree by weaving branches into a platform, often with a pillow of softer foliage. They sometimes make a separate nest for midday naps. They typically travel on all fours (knuckle-walking) on the ground but are agile climbers. Chimps can also walk bipedally for short distances, usually when carrying objects.',
    status: {
      lifespan: '40–50 years',
      weight: 'Males ~40–60 kg, Females ~32–47 kg',
      conservation: 'Endangered',
    },
    relatedSpecies: ['mountain-gorilla', 'orangutan'],
  },
  {
    slug: 'giraffe',
    name: 'Giraffa camelopardalis',
    category: 'Mammals',
    commonName: 'Giraffe',
    description: 'The world’s tallest land animal, an icon of the African savanna recognizable by its extremely long neck and legs.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The giraffe is the world’s tallest land animal, an icon of the African savanna recognizable by its extremely long neck and legs, and patchwork coat of reddish-brown patches separated by pale lines. A giraffe’s towering height (up to 5.5 m for males) allows it to browse foliage that other herbivores can’t reach. Despite having a long neck (~2 m), giraffes still have only seven neck vertebrae (like most mammals), but each vertebra is greatly elongated. They have large eyes and excellent vision to spot predators from afar. A giraffe’s heart, weighing up to 11–12 kg, generates blood pressure twice that of humans to pump blood up that long neck to the brain. Specialized valves in neck arteries and a sponge-like rete mirabile at the brain’s base help regulate blood flow, so they don’t faint when lowering their head. Giraffes move in a unique gait (walking by moving both legs on one side, then the other) and can gallop at up to ~60 km/h in short bursts. Their graceful, slow-motion stride and gentle demeanor make them a favorite sight on safari.',
    habitat: 'Giraffes inhabit sub-Saharan African savannas, woodlands, and open acacia forests. They prefer areas with plenty of tall trees or bushes (especially acacias) for browsing, but also wide open spaces to spot danger. Giraffes are spread across various regions of Africa, and currently classified into several species or subspecies (like Masai, Reticulated, Southern, Northern giraffes, etc.) with patterns and ranges varying. They generally avoid dense rainforests (where maneuvering their height is difficult) and true deserts with no trees. Instead, they thrive in thornbush savannas, dry open forests, or mixed shrublands where their food is abundant year-round. Giraffes often stay near water sources but can go weeks without drinking, getting moisture from leaves.',
    diet: 'Herbivorous browsers, giraffes feed predominantly on leaves, buds, and shoots of woody plants. Acacia trees are a staple – giraffes deftly use their long, prehensile tongue (about 45 cm long, bluish-black in color to prevent sunburn) and flexible upper lip to pull foliage, carefully navigating around thorns. They consume a variety of trees and shrubs (like acacias, combretum, and wild apricot), and also eat flowers, fruits (when in season), and occasionally grasses or herbs. An adult giraffe eats roughly 30 kg of leaves per day. Their height gives them access to an uncontested food supply about 2–5 m off the ground, above where kudu or other browsers can reach. Interestingly, giraffes have tough mouths and thick saliva that protect against thorns. When water is available, giraffes drink, but their splayed-legged, head-lowered posture at watering holes is vulnerable – so they drink infrequently (every few days) and rely mostly on moisture from leaves. They ruminate like cattle; after a feeding bout, they often rest and chew cud, which maximizes nutrient extraction from fibrous plants.',
    behavior: 'Giraffes are somewhat social but without strong group bonds. They typically live in loose herds of a few individuals up to 20 or more, but group composition can change fluidly (fission-fusion dynamics). They do not have a rigid herd structure – no single leader or fixed memberships – though females often associate with others when raising calves, and males form bachelor groups or wander alone. Giraffes are generally quiet (long thought to be mostly silent, though they do produce low-frequency hums at night and occasional snorts or bleats). A day in the life of a giraffe involves a lot of feeding (they browse throughout the day and even some at night, given their need for large quantities of food). They sleep very little – often just a few minutes at a time, totaling maybe 1–2 hours in 24 (and often standing up). Dominance in males is established by ritualized combat known as “necking.” Males swing their necks and deliver heavy blows with their horn-like ossicones (and heads) to an opponent. These bouts can be slow and graceful or intensify with loud thuds – the male who best withstands or delivers hits wins rank and breeding access. Serious injuries from necking are rare, but occasionally a heavy blow can knock a rival down. Females give birth standing up, after a ~15-month gestation. The calf, about 1.8 m tall at birth, drops to the ground (a 2 m fall!) and, remarkably, is on its feet within an hour. Mothers guard their calves diligently; multiple calves may form a “nursery group” watched by one female while others feed nearby. Calves are vulnerable to predators like lions, hyenas, and leopards – mothers will kick powerfully to defend them (a giraffe’s kick can be deadly, capable of breaking a lion’s jaw or skull). Giraffes use their height and keen vision as a defense advantage – they often spot predators from far and will stare intently, sometimes snorting, which can alert other animals as well. When threatened, adult giraffes can gallop away at high speed or stand and fight by kicking. Aside from mothers with calves, most predators avoid adult giraffes due to their size and dangerous limbs.',
    status: {
      lifespan: '20-25 years',
      weight: 'Up to 1,200 kg (2,645 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['african-elephant'],
  },
  {
    slug: 'hippopotamus',
    name: 'Hippopotamus amphibius',
    category: 'Mammals',
    commonName: 'Hippopotamus',
    description: 'A massive semi-aquatic mammal, known for its large size and territorial nature.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The common hippopotamus is a massive semi-aquatic mammal, famed for its barrel-shaped body, enormous gape, and unpredictable temperament. Despite their rotund, almost comical appearance, hippos are among Africa’s most dangerous animals – extremely territorial in water and equipped with huge canines that can inflict grievous wounds. An adult hippo can weigh as much as 1.5–3 tons and measure around 3.5 m in length. They have hairless, thick gray-brown skin that secretes a unique red-tinted sweat which acts as a natural sunscreen and antiseptic (sometimes called "blood sweat," though it’s neither blood nor exactly sweat). Their eyes, ears, and nostrils are positioned high on the head, allowing them to see and breathe while mostly submerged. Hippos spend days wallowing in rivers or lakes to keep cool, and emerge at night to graze on land. Though related to cetaceans (whales and dolphins) in evolutionary terms, on land their short, stumpy legs can surprisingly outrun a human over short distances. They cannot swim in the conventional sense but propel themselves off the bottom and glide. With their unique amphibious lifestyle and formidable presence, hippos play a major role in their ecosystem, both as mega-herbivores and ecosystem engineers (their dung and movements affect river habitats).',
    habitat: 'Hippos are found in sub-Saharan Africa, wherever freshwater is sufficient year-round. They need permanent rivers, lakes, or swamps with adjacent grasslands for grazing. Typical habitats include slowmoving rivers in savanna regions, the fringes of large wetlands, oxbow lakes, and estuaries. By day, hippos reside in water (or muddy wallows) that is deep enough to cover most of their bodies, protecting their sensitive skin from sun and keeping their massive bodies cool. They prefer areas with gently sloping banks or sandbars where they can bask or exit easily. At night, they travel on land – sometimes up to several kilometers – to feed in grasslands or floodplain meadows. Historically, hippos were widespread across Africa’s rivers (and even in the Nile Delta into historical times), but now they are mostly confined to protected areas and remote wetlands.',
    diet: 'Hippos are herbivores with a diet primarily of grass. At night, a hippo leaves the water and grazes on grasses, often creating clear “hippo paths” from the water to feeding areas. An adult hippo can consume about 30–40 kg of vegetation nightly. They have a tough digestive system and can subsist on coarse terrestrial grasses that other animals might not favor. Though bulk grazers, hippos have been observed to browse occasionally on softer reeds or fallen fruit, but this is not a significant part of their diet. They do not typically eat aquatic plants (their feeding is mostly on land). Hippos have a unique physiology where they ferment plant matter in their gut, but unlike ruminants, they do not chew cud. Interestingly, despite their fierce teeth, the large canine and incisor tusks are used for fighting, not feeding; they mainly use their broad lips to clip grass. Hippos can go for extended periods without feeding if required (staying in water during droughts), living off fat reserves. They generally drink large amounts of water while in their aquatic habitat, but their skin also needs moisture – hence their constant immersion.',
    behavior: 'Hippos are social to a degree, typically living in groups (often called pods, bloats, or schools) of a few to dozens of individuals. A dominant adult bull (male) usually presides over a stretch of river or a part of a lake, controlling a territory that often contains several cows (females) and their young. In large water bodies, many hippos share space somewhat peacefully, with a clear hierarchy among males. They spend daylight hours packed together in water, often shoulder to shoulder or lying on each other in shallow spots. They appear lethargic by day, merely bobbing to breathe – their nostrils automatically seal underwater and they can hold breath ~5 minutes. Remarkably, hippos even sleep underwater, reflexively bobbing up to breathe without waking. Social interactions range from amicable (resting in contact, communal defecation areas) to highly aggressive. Bulls guard their section of water fiercely. Territory boundaries are marked by dung spraying: hippos spin their tails while defecating, flinging dung to mark bushes and rocks at the water’s edge – a smelly bulletin board advertising their presence. Confrontations between males involve impressive displays: opening the mouth nearly 150° in a gape that shows off formidable tusks, roaring and chuffing, and splashing. Fights, when they occur, can be brutal – slashing with lower tusks that can inflict deep gashes or puncture wounds (often seen as scars on older bulls). Most disputes are settled by display, however, and subordinate bulls or bachelor males typically yield or stay in peripheral areas. Hippo vocalizations are notable: they honk, grunt, and produce a loud “wheeze-honk” call that can carry over water – one of the only mammal calls that resonates in both air and water simultaneously. A chorus of honking at dusk or dawn is characteristic of a hippo group. They also snort and blow water when surfacing. Despite their bulk, hippos can run swiftly on land for short distances, reaching speeds around 30 km/h (18 mph) – hence humans are advised not to get between a hippo and water. They are responsible for many human injuries in Africa, usually when people unwittingly come too close (especially between a hippo and deep water, or surprising one on land at night). Female hippos are particularly aggressive if they sense a threat to their calves. Reproduction occurs in water: a bull mates with cows in his territory. After an 8-month gestation, a cow gives birth underwater to a single calf (weighing ~30–50 kg). The calf must swim to the surface for its first breath. Mother and calf stay close; the calf often rests on mom’s back in shallows or swims alongside. Mothers can be extremely defensive – they will attack crocodiles, lions, or anything perceived as a danger to their young. Calves are weaned around 8 months but remain with the mother for a couple of years or until she calves again.',
    status: {
      lifespan: '35-40 years',
      weight: 'Up to 2,000 kg (4,400 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: [],
  },
  {
    slug: 'rhinoceros',
    name: 'Ceratotherium simum / Diceros bicornis',
    category: 'Mammals',
    commonName: 'Rhinoceros',
    description: 'One of the world’s largest land mammals, known for its prehistoric appearance and prominent nose horns.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Rhinoceroses are among the world’s largest land mammals, known for their prehistoric appearance and prominent nose horns. Africa hosts two species: the white rhinoceros (which is gray, not white – name is a corruption of Dutch wijd, referring to its wide lip) and the smaller black rhinoceros (also gray in color). Both have two horns on the snout made of keratin (the same material as hair and fingernails). Rhinos are built like armored tanks: barrel-chested, with thick protective skin (up to 5 cm thick in places), pillar-like legs, and a relatively small brain for their size. Despite poor eyesight (they have notoriously short visual range, maybe 30 m), they have excellent hearing and an acute sense of smell. Rhinos are herbivorous and can be surprisingly quick and agile for their size – capable of running 45–50 km/h in short bursts. Their temperament ranges from placid to extremely aggressive, especially if startled or if a female perceives a threat to her calf. They often display a curious mix of behaviors: wallowing in mud to cool and protect their skin, and using communal dung piles (“middens”) as scent posts to communicate with other rhinos.',
    habitat: 'White rhinos prefer open savannas, grasslands, and shrublands with waterholes nearby – they are grazers that need abundant grass. They primarily occur in Southern Africa (South Africa, Namibia, Zimbabwe, Kenya, etc.) and were reintroduced to some areas after near-extinction. Black rhinos, being browsers, thrive in bushy savanna, woodlands, and semi-arid scrublands where they can feed on shrubs and small trees. Their range was historically across much of sub-Saharan Africa, but now mainly in Eastern and Southern Africa. Both species need access to water for drinking (especially white rhinos which drink daily when available) and for wallowing in mud. Rhinos make use of shade trees or thickets to escape midday heat. They can survive in surprisingly dry environments (black rhinos in particular can go a few days without water by feeding on succulent plants). Habitat fragmentation is a concern – rhinos need large territories, and fences can hinder their movements.',
    diet: 'All rhinos are herbivores, but their feeding strategies differ. White rhinos are almost exclusively grazers. They have a broad, square upper lip adapted to mowing grass – they wander with head down, cropping large quantities of grass. An adult white rhino can graze for many hours a day, consuming dozens of kilograms of grass. They prefer short grasses but will eat taller grasses if needed, and sometimes browse a bit of herbs. Black rhinos are browsers. They possess a pointed, prehensile upper lip that acts like a mini trunk to grasp leaves and twigs. Black rhinos feed on a variety of woody plants, leaves, buds, and fruits from shrubs and trees – e.g., they enjoy acacia pods, euphorbias, and other succulents. They often cause a noticeable “pruned” effect on the vegetation at browsing height. Rhinos have a simple stomach and rely on hindgut fermentation (like horses) to digest fibrous plant matter, hence they favor quality forage. Both species visit salt licks if available, indicating a need for minerals. They typically drink daily if water is at hand, but black rhinos can endure dry spells using moisture from plants.',
    behavior: 'Rhinos are mostly solitary or live in small, loosely structured groups. White rhinos tend to be more social: females and subadults may form small groups of up to 6–7, and they are more tolerant of each other in open plains. Dominant bulls are territorial, marking with dung and urine, and defending an area that may overlap several females’ home ranges. Subordinate bulls without territory roam or gather in bachelor groups. Black rhinos are more solitary and temperamental. They typically keep apart, coming together only for mating or a mother with calf. If two black rhinos encounter each other, they may engage in ritualized posturing, snorts, and possibly charges – serious fights can result in gore wounds from their horns. They utilize communal dung piles; by smelling these middens, rhinos get information on other individuals in the area (age, sex, reproductive status). Both species have poor eyesight and can be easily startled if approached upwind (they might not see a motionless person at 30 m). However, once alerted (often by scent or sound), they can charge with astonishing speed. Black rhinos in particular have a reputation for unpredictable aggression – they may charge perceived threats (even vehicles or trees, sometimes) with little provocation. Rhinos spend a good portion of the day resting, especially during hot noon hours. They love wallowing in muddy pools – coating their skin with mud helps cool them and acts as a barrier against parasites and sunburn. After the mud dries, they rub against rocks or logs to scratch off ticks and insects (oxpecker birds also help by picking parasites off rhinos’ hides). Territorial bulls patrol and mark their area by spraying urine and spreading dung with their feet. They have a variety of vocalizations: grunts and snorts when agitated, trumpet-like bleats (especially by calves or in courtship), and a loud puff or “blow” as an alarm. Black rhinos have a characteristic high-pitched snort-snarl if threatened. Mothers are protective but generally only aggressive if a calf is threatened. Calves stay with their mothers for ~2–3 years until the next calf is born, after which the youngster is usually chased away. Young rhinos (especially black rhinos) can be playful – engaging in mock charges, horn dueling with shrubbery, or running in circles.',
    status: {
      lifespan: '35-50 years',
      weight: 'White: ~2,300kg; Black: ~1,350kg',
      conservation: 'Critically Endangered (Black) & Near Threatened (White)',
    },
    relatedSpecies: ['african-elephant'],
  },
  {
    slug: 'polar-bear',
    name: 'Ursus maritimus',
    category: 'Mammals',
    commonName: 'Polar Bear',
    description: 'The mighty nomad of the Arctic ice, the world’s largest bear and a marine mammal.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The polar bear is the world\'s largest bear, an apex predator in a world of ice and snow. Though their fur appears white, each hair is actually transparent and hollow, helping trap heat. Beneath their fur, a polar bear’s skin is black to absorb heat. They have massive paws that act like snowshoes and paddles. Polar bears are classified as marine mammals; their Latin name maritimus means “of the sea.”',
    habitat: 'Polar bears are found in the Arctic regions of Canada, Russia, Greenland, Norway, and the United States (Alaska). They live on sea ice, which they use as a platform to hunt seals at open leads or breathing holes. Their habitat is intrinsically linked to the presence of the frozen ocean.',
    diet: 'Their primary prey is seals, particularly ringed and bearded seals, which have a high fat content. A polar bear’s powerful sense of smell can detect a seal from over a kilometer away. They need to eat a lot of calorie-rich blubber to sustain themselves in the cold.',
    behavior: 'Polar bears lead mostly solitary lives, with the exception of mothers raising cubs. Mating occurs in spring, after which a pregnant female builds a snow den to give birth during winter. She survives on her fat reserves while nursing her cubs. When they emerge in spring, she teaches them how to stalk and hunt across the ice. Polar bears are marathon swimmers, capable of covering long distances in frigid waters.',
    status: {
      lifespan: '15-30 years',
      weight: '400-700 kg (males), 150-350 kg (females)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['grizzly-bear'],
  },
  {
    slug: 'grizzly-bear',
    name: 'Ursus arctos horribilis',
    category: 'Mammals',
    commonName: 'Grizzly Bear',
    description: 'The formidable guardian of the North American wilds, feared and revered for its strength and tenacity.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Grizzly bears, a subspecies of the brown bear, roam the forests, mountains, and tundra of North America. They wear a shaggy coat varying from sandy brown to almost black, often with white-tipped (“grizzled”) fur on their backs and shoulders that gives them their name. One of their most distinctive physical features is the muscular hump over their shoulders – this is a powerhouse of muscle attached to the spine, giving grizzlies the force for digging and swinging their massive paws.',
    habitat: 'Grizzly bears inhabit the forests, mountains, and tundra of North America. They have a home range that can span hundreds of square kilometers. In colder climates, grizzlies enter a deep torpor in dens from about November to March.',
    diet: 'Grizzlies are omnivores with a diverse diet: they’ll graze on berries, nuts, and grass, dig for rodents, devour carrion or prey they’ve killed (such as elk calves), and in some regions, gorge on spawning salmon in rivers.',
    behavior: 'Grizzly bears are generally solitary and avoid humans. They spend a lot of time foraging to build up fat for winter. Females often give birth during hibernation to tiny cubs, who they fiercely protect for the next 2-3 years. Despite their bulk, they can run at speeds of about 35 miles per hour (56 km/h).',
    status: {
      lifespan: '20-25 years',
      weight: 'Up to 300 kg (660 lbs)',
      conservation: 'Threatened in the contiguous US, but stable in Alaska and Canada.',
    },
    relatedSpecies: ['polar-bear'],
  },
  {
    slug: 'zebra',
    name: 'Equus quagga',
    category: 'Mammals',
    commonName: 'Zebra',
    description: 'The painted horse of Africa’s plains, adorned in bold stripes that dazzle the eye and confuse the predator.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Zebras are instantly recognizable with their striking black-and-white striped coats. The plains zebra, common across East and Southern Africa’s savannahs, often gathers in herds so dazzling it’s like a mirage of flickering stripes under the sun. The leading theories for their stripes are that they may help with thermoregulation, deter biting flies, or confuse predators by creating a motion dazzle when many zebras run together.',
    habitat: 'Zebras are social animals, typically found in family groups (harems) consisting of one stallion, several mares, and their foals. Multiple families often join to form large herds, especially during migrations like the great Serengeti migration.',
    diet: 'Zebras are grazing herbivores. They have strong teeth and gut bacteria that allow them to subsist on tougher grasses than many other herbivores can handle, often grazing down older, fibrous grass, which makes way for other species like wildebeest.',
    behavior: 'Each zebra’s stripe pattern is unique. Newborn zebras can run within an hour of birth. They communicate with barks, whinnies, and a signature high-pitched yipping alarm call. They defend themselves with powerful kicks that can break a predator’s jaw.',
    status: {
      lifespan: '20-25 years',
      weight: '220-450 kg (485-992 lbs)',
      conservation: 'Near Threatened',
    },
    relatedSpecies: ['lion'],
  },
  {
    slug: 'scarlet-macaw',
    name: 'Ara macao',
    category: 'Birds',
    commonName: 'Scarlet Macaw',
    description: 'A large, colorful parrot with a vibrant plumage of red, yellow, and blue.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The Scarlet Macaw is one of the most beautiful and iconic parrots. Its brilliant colors make it a standout in the rainforest canopy. They are highly intelligent and social birds.',
    habitat: 'They inhabit humid evergreen forests in the American tropics, from southern Mexico to Peru, Colombia, Bolivia, Venezuela and Brazil.',
    diet: 'Their diet consists mainly of fruits, nuts, and seeds. Their strong beaks are perfect for cracking open hard nuts and seeds.',
    behavior: 'Scarlet Macaws mate for life. They are often seen flying in pairs or family groups. They nest in the cavities of tall, dead trees and can be very noisy.',
    status: {
      lifespan: '40-50 years, up to 75 in captivity',
      weight: 'About 1 kg (2.2 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: ['blue-and-yellow-macaw'],
  },
  {
    slug: 'bald-eagle',
    name: 'Haliaeetus leucocephalus',
    category: 'Birds',
    commonName: 'Bald Eagle',
    description: 'The majestic national bird of the United States, known for its white head and tail.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The bald eagle is a bird of prey found in North America. A sea eagle, it has two known subspecies and forms a species pair with the white-tailed eagle. Its range includes most of Canada and Alaska, all of the contiguous United States, and northern Mexico.',
    habitat: 'They are found near large bodies of open water with an abundant food supply and old-growth trees for nesting, such as coasts, rivers, and large lakes.',
    diet: 'Their primary food is fish, which they swoop down and snatch from the water. They also eat other birds, small mammals, and carrion.',
    behavior: 'Bald eagles build some of the largest nests of any bird, often several feet across. They are monogamous and believed to mate for life. They are powerful fliers, and can reach speeds of up to 100 mph when diving.',
    status: {
      lifespan: 'About 20 years in the wild',
      weight: '3 to 6.3 kg (6.6 to 14 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: [],
    videoUrl: 'https://www.youtube.com/embed/9T-g3gGUTLw',
  },
  {
    slug: 'blue-and-yellow-macaw',
    name: 'Ara ararauna',
    category: 'Birds',
    commonName: 'Blue-and-yellow Macaw',
    description: 'A large South American parrot with blue top parts and yellow underparts.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The blue-and-yellow macaw is a large South American parrot with mostly blue top parts and light orange underparts. They are popular in aviculture because of their striking color, intelligence, and ability to mimic human speech.',
    habitat: 'It is found in woodland and tropical rainforest in South America.',
    diet: 'Their diet consists of seeds, nuts, fruits, and vegetation.',
    behavior: 'They are social birds that often form lifelong pair bonds. They are known for their loud calls and playful nature.',
    status: {
      lifespan: '30-35 years in the wild',
      weight: '0.9-1.5 kg (2-3.3 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: ['scarlet-macaw'],
  },
  {
    slug: 'emperor-penguin',
    name: 'Aptenodytes forsteri',
    category: 'Birds',
    commonName: 'Emperor Penguin',
    description: 'The tallest and heaviest of all living penguin species, endemic to Antarctica.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Emperor penguins are famed for their incredible breeding journeys. They are the only penguin species that breeds during the Antarctic winter, trekking 50-120 km (31-75 mi) over the ice to breeding colonies.',
    habitat: 'The icy coasts of Antarctica. They spend their entire lives on Antarctic ice and in its surrounding waters.',
    diet: 'Primarily fish, but also krill and squid. They can dive to depths of over 500m (1,640 ft) to find food.',
    behavior: 'Highly social animals, they form vast colonies to huddle together for warmth against the extreme cold. Males incubate a single egg for two months during the winter without eating.',
    status: {
      lifespan: '15-20 years',
      weight: '22 to 45 kg (49 to 99 lbs)',
      conservation: 'Near Threatened',
    },
    relatedSpecies: [],
  },
  {
    slug: 'komodo-dragon',
    name: 'Varanus komodoensis',
    category: 'Reptiles',
    commonName: 'Komodo Dragon',
    description: 'The world\'s largest lizard, a fearsome predator with a venomous bite.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The Komodo dragon is a species of lizard found in the Indonesian islands of Komodo, Rinca, Flores, and Gili Motang. A member of the monitor lizard family Varanidae, it is the largest living species of lizard.',
    habitat: 'They prefer hot and dry places and typically live in dry, open grassland, savanna, and tropical forest at low elevations.',
    diet: 'Komodo dragons are carnivores. They are formidable predators and will eat almost anything, including deer, pigs, smaller dragons, and even large water buffalo.',
    behavior: 'They are solitary animals, coming together only to breed and eat. They can run up to 20 kph (12 mph) in short bursts. Their bite delivers a potent mix of venom and bacteria.',
    status: {
      lifespan: 'Up to 30 years',
      weight: 'Around 70 kg (150 lbs)',
      conservation: 'Endangered',
    },
    relatedSpecies: [],
    videoUrl: 'https://www.youtube.com/embed/rGN8K-9V9UQ',
  },
  {
    slug: 'green-sea-turtle',
    name: 'Chelonia mydas',
    category: 'Reptiles',
    commonName: 'Green Sea Turtle',
    description: 'A large, migratory sea turtle named for the green color of its fat and cartilage.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The green sea turtle is a species of large sea turtle of the family Cheloniidae. It is the only species in the genus Chelonia. They are found in tropical and subtropical seas around the world.',
    habitat: 'They are primarily found in tropical and subtropical waters. They alternate between foraging grounds in shallow, coastal areas and the beaches where they were born to lay their own eggs.',
    diet: 'As adults, green sea turtles are unique among sea turtles in that they are primarily herbivores, feeding on seagrasses and algae. Juveniles are omnivores.',
    behavior: 'Green sea turtles migrate long distances between feeding grounds and nesting beaches. Females return to the same beaches where they were born to lay their eggs.',
    status: {
      lifespan: '80 years or more',
      weight: 'Up to 190 kg (420 lbs)',
      conservation: 'Endangered',
    },
    relatedSpecies: ['leatherback-sea-turtle'],
  },
  {
    slug: 'leatherback-sea-turtle',
    name: 'Dermochelys coriacea',
    category: 'Reptiles',
    commonName: 'Leatherback Sea Turtle',
    description: 'The largest of all living turtles and is the fourth-heaviest modern reptile.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The leatherback sea turtle, sometimes called the lute turtle or leathery turtle, is the largest of all living turtles. It can easily be differentiated from other modern sea turtles by its lack of a bony shell, hence the name. Instead, its carapace is covered by skin and oily flesh.',
    habitat: 'They are found in the open ocean and have the widest distribution of any sea turtle, ranging from the tropics to sub-polar regions.',
    diet: 'Their diet consists almost entirely of jellyfish and other soft-bodied invertebrates.',
    behavior: 'They are the most migratory of all sea turtle species, undertaking long-distance migrations between feeding and nesting grounds.',
    status: {
      lifespan: 'Around 30 years in the wild',
      weight: '250 to 700 kg (550 to 1,540 lb)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['green-sea-turtle'],
  },
  {
    slug: 'saltwater-crocodile',
    name: 'Crocodylus porosus',
    category: 'Reptiles',
    commonName: 'Saltwater Crocodile',
    description: 'The largest living reptile and crocodilian known to mankind.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The saltwater crocodile is a formidable and opportunistic hypercarnivorous apex predator. They are known for their immense size and aggressive nature.',
    habitat: 'They inhabit brackish and freshwater habitats from eastern India, Southeast Asia, and northern Australia.',
    diet: 'They consume a wide range of prey, including fish, mammals, and birds. They are ambush predators, waiting for potential prey to get close before launching a swift and powerful attack.',
    behavior: 'Saltwater crocodiles are highly territorial. They communicate through a variety of vocalizations and are most active in the warmer months.',
    status: {
      lifespan: 'Up to 70 years',
      weight: 'Up to 1,000 kg (2,200 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: [],
  },
  {
    slug: 'clownfish',
    name: 'Amphiprioninae',
    category: 'Marine Life',
    commonName: 'Clownfish',
    description: 'A small, brightly colored fish famous for its symbiotic relationship with sea anemones.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Clownfish, or anemonefish, are small fish found in warmer waters of the Indian and Pacific oceans. They are known for their striking orange and white patterns. There are about 30 recognized species.',
    habitat: 'They form a symbiotic relationship with sea anemones. The clownfish is protected from the anemone\'s stinging cells by a layer of mucus, and in turn, the clownfish defends the anemone from predators.',
    diet: 'Clownfish are omnivores. They eat a variety of small invertebrates and algae, as well as undigested food from their host anemones.',
    behavior: 'Clownfish live in a strict hierarchy within a single anemone. The largest and most aggressive female is at the top. All clownfish are born male; they have the ability to change sex to become the dominant female if the previous one dies.',
    status: {
      lifespan: '6-10 years',
      weight: 'Up to 250 grams',
      conservation: 'Not evaluated for most species, but threatened by reef degradation.',
    },
    relatedSpecies: ['orca'],
  },
  {
    slug: 'great-white-shark',
    name: 'Carcharodon carcharias',
    category: 'Marine Life',
    commonName: 'Great White Shark',
    description: 'One of the ocean\'s most powerful predators, known for its size and serrated teeth.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The great white shark is a species of large mackerel shark which can be found in the coastal surface waters of all the major oceans. It is notable for its size, with mature female individuals growing up to 6.1 m (20 ft) in length.',
    habitat: 'They are found in cool, coastal waters throughout the world. They have been recorded at depths as great as 1,200 m (3,900 ft).',
    diet: 'Young great whites eat fish, rays, and other sharks. Adults feed on larger prey, including pinnipeds (like sea lions and seals), small-toothed whales (like dolphins), and sea turtles.',
    behavior: 'Great whites are solitary and highly migratory, with some individuals making trans-oceanic journeys. They are apex predators, with only orcas known to prey on them.',
    status: {
      lifespan: 'Estimated 70 years or more',
      weight: 'Up to 2,268 kg (5,000 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['orca'],
  },
  {
    slug: 'orca',
    name: 'Orcinus orca',
    category: 'Marine Life',
    commonName: 'Orca (Killer Whale)',
    description: 'A toothed whale belonging to the oceanic dolphin family, of which it is the largest member.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Orcas, or killer whales, are apex predators found in all of the world\'s oceans. They are known for their complex social structures, hunting techniques, and vocal behaviors.',
    habitat: 'They are found in a variety of marine environments, from Arctic and Antarctic regions to tropical seas.',
    diet: 'Their diet is diverse and includes fish, seals, sea lions, dolphins, and even large whales.',
    behavior: 'Orcas are highly social and live in family groups called pods. They communicate with a wide range of clicks, whistles, and pulsed calls.',
    status: {
      lifespan: '50-90 years',
      weight: 'Up to 5,400 kg (12,000 lbs)',
      conservation: 'Data Deficient',
    },
    relatedSpecies: ['great-white-shark', 'clownfish'],
  },
  {
    slug: 'bottlenose-dolphin',
    name: 'Tursiops truncatus',
    category: 'Marine Life',
    commonName: 'Bottlenose Dolphin',
    description: 'A well-known species of dolphin recognized for its intelligence and charisma.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Bottlenose dolphins are highly intelligent marine mammals known for their playful behavior and complex social lives. Their curved mouths give the appearance of a friendly, permanent smile.',
    habitat: 'Found in temperate and tropical waters worldwide, inhabiting both coastal and deep-water environments.',
    diet: 'They are skilled hunters, feeding on a varied diet of fish, squid, and crustaceans. They often hunt cooperatively.',
    behavior: 'They live in social groups called pods and communicate using a complex system of squeaks, whistles, and body language. They are known for their acrobatic leaps out of the water.',
    status: {
      lifespan: '40-60 years',
      weight: '150 to 650 kg (330 to 1,430 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: ['orca'],
  },
];

export const categories = ['Mammals', 'Birds', 'Reptiles', 'Marine Life'];

export const getAnimalBySlug = (slug: string) => animals.find(a => a.slug === slug);
export const getAnimalsByCategory = (category: string) => {
 return animals.filter(a => a.category.toLowerCase().replace(/\s+/g, '-') === category);
};

    
