
export type Animal = {
  slug: string;
  name: string;
  category: 'Mammals' | 'Birds' | 'Reptiles' | 'Marine Life';
  commonName: string;
  description: string;
  imageUrl: string;
  bannerUrl: string;
  overview: string;
  habitat: string;
  diet: string;
  behavior: string;
  status: {
    lifespan: string;
    weight: string;
    conservation: string;
  };
  relatedSpecies: string[];
  videoUrl?: string;
};

export const animals: Animal[] = [
  {
    slug: 'african-elephant',
    name: 'Loxodonta africana',
    category: 'Mammals',
    commonName: 'African Elephant',
    description: 'The largest land animal, known for its intelligence and complex social structure.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'African elephants are the largest land animals on Earth. They are slightly larger than their Asian cousins and can be identified by their larger ears that are shaped somewhat like the continent of Africa.',
    habitat: 'Found in a variety of habitats including savannas, forests, and marshlands across Africa.',
    diet: 'Elephants are herbivores, spending much of their day eating. Their diet consists of grasses, leaves, bark, fruit, and a variety of foliage.',
    behavior: 'They live in complex social structures led by a matriarch. Elephants are known for their high intelligence, long memory, and deep family bonds. They communicate using a wide variety of sounds.',
    status: {
      lifespan: '60-70 years',
      weight: 'Up to 6,000 kg (13,000 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: [],
    videoUrl: 'https://www.youtube.com/embed/nS_3Uv_2A7c',
  },
  {
    slug: 'siberian-tiger',
    name: 'Panthera tigris tigris',
    category: 'Mammals',
    commonName: 'Siberian Tiger',
    description: 'The world\'s largest cat, a powerful predator of the Russian Far East.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The Siberian tiger, also known as the Amur tiger, is a tiger population of the subspecies Panthera tigris tigris native to the Russian Far East and Northeast China. It is the largest of all wild cats.',
    habitat: 'They live primarily in the birch forests of Russia\'s Far East, though some exist in China and North Korea.',
    diet: 'Siberian tigers are carnivores, preying on animals like wild boar, red deer, moose, and roe deer. They are powerful hunters capable of taking down large prey.',
    behavior: 'Tigers are solitary hunters, using their distinctive striped coat as camouflage. They are territorial and mark their large home ranges with urine and scratches.',
    status: {
      lifespan: '10-15 years in the wild, up to 20 in captivity',
      weight: 'Up to 300 kg (660 lbs)',
      conservation: 'Endangered',
    },
    relatedSpecies: ['lion'],
  },
  {
    slug: 'red-panda',
    name: 'Ailurus fulgens',
    category: 'Mammals',
    commonName: 'Red Panda',
    description: 'A small mammal native to the eastern Himalayas and southwestern China.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The red panda, with its reddish-brown fur, long, shaggy tail, and waddling gait, is a solitary animal, mainly active from dusk to dawn. Despite its name, it is not closely related to the giant panda.',
    habitat: 'Temperate forests with bamboo understories in the Himalayas.',
    diet: 'Primarily eats bamboo, but also eggs, birds, and insects.',
    behavior: 'Arboreal, skillful and acrobatic climbers that spend most of their time in trees.',
    status: {
      lifespan: '8-10 years',
      weight: '3-6 kg (7-14 lbs)',
      conservation: 'Endangered',
    },
    relatedSpecies: ['giant-panda'],
  },
  {
    slug: 'cheetah',
    name: 'Acinonyx jubatus',
    category: 'Mammals',
    commonName: 'Cheetah',
    description: 'The world’s fastest land animal, renowned for its speed and grace.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The cheetah is the world’s fastest land animal, renowned for its speed and grace. It has a lean build with long legs, a flexible spine, and semi-retractable claws – all adaptations for running down prey in bursts of astonishing acceleration. A cheetah can sprint from 0 to 95 km/h in mere seconds and reach top speeds around 100–120 km/h (about 60–75 mph), although only for short distances (~500 m). Its coat is tan with black spots, providing camouflage in the grasslands. Unlike other big cats, cheetahs do not roar; they purr and chirp, and they are relatively lightly built, built for speed over strength.',
    habitat: 'Cheetahs favor open savannahs, grasslands, and arid deserts where they can make full use of their speed in open terrain. Historically ranging throughout Africa, the Middle East, and into India, they are now mostly found in sub-Saharan Africa with a small critically endangered population in Iran. They thrive in areas with good visibility and plentiful prey, such as expansive plains or lightly wooded bushveld.',
    diet: 'A carnivore that relies on speed, the cheetah primarily hunts medium-sized ungulates. Common prey include impalas, gazelles (like Thomson’s gazelle), springbok, young wildebeest, and hares. Cheetahs are diurnal hunters (active mainly in early morning or late afternoon) to avoid competition with stronger nocturnal predators. They use a stealthy stalk to get within sprinting distance, then explode in a chase. A successful cheetah will often trip its prey with a swipe of the paw and suffocate it with a bite to the throat. Cheetahs eat quickly to avoid losing their kill – they’re frequently displaced by lions, hyenas, or leopards, being less powerful fighters.',
    behavior: 'Unlike lions, cheetahs are solitary or live in small family groups. Adult females are solitary except when raising cubs. Males may form small coalitions (often littermates) that stay together for life, cooperating to defend a territory and hunt. Cheetahs do not have the strength to fight larger carnivores and often surrender kills to them. They avoid confrontation and rely on their incredible acceleration and agility to survive. Cheetah cubs have a mantle of long, silvery fur on their backs, thought to mimic the appearance of a honey badger (possibly to deter some predators). Mothers raise cubs alone, moving them frequently and teaching them hunting skills.',
    status: {
      lifespan: '10-12 years',
      weight: '35-60 kg',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['lion', 'jaguar'],
  },
  {
    slug: 'giant-panda',
    name: 'Ailuropoda melanoleuca',
    category: 'Mammals',
    commonName: 'Giant Panda',
    description: 'A bear native to south-central China, known for its iconic black-and-white coat.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The giant panda is a beloved bear species recognized by its distinct black-and-white coloring. Despite being classified as a carnivore, its diet is over 99% bamboo.',
    habitat: 'Mountainous regions of central China, primarily in Sichuan, but also in neighboring Shaanxi and Gansu provinces.',
    diet: 'Almost entirely bamboo. They must eat 26 to 84 pounds of it every day, depending on what part of the bamboo they are eating.',
    behavior: 'Giant pandas are generally solitary. They have a highly developed sense of smell that males use to avoid each other and to find females for mating in the spring.',
    status: {
      lifespan: 'About 20 years in the wild',
      weight: 'Up to 125 kg (275 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['red-panda'],
  },
  {
    slug: 'lion',
    name: 'Panthera leo',
    category: 'Mammals',
    commonName: 'Lion',
    description: 'The "king of the jungle," a social big cat living in prides, known for its powerful roar and majestic mane.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The African lion is often called the "king of the jungle," although it primarily inhabits savannahs and grasslands. Male lions are unique among big cats for their impressive manes, which grow darker and fuller with age. Lions are the second-largest big cats after tigers and live in social groups called prides. Both males and females can produce a thunderous roar audible up to 8 km away, a sound that asserts territory and helps pride members find one another. These apex predators symbolize strength and have been revered in human culture for millennia.',
    habitat: 'Lions once roamed across Africa, Asia, and Europe, but today they survive mainly in sub-Saharan Africa (with a small population of Asiatic lions in India). They prefer grassy plains, savannahs, open woodlands, and scrub, where sufficient prey is available. Shade from scattered trees or thickets offers relief from midday heat.',
    diet: 'Obligate carnivores, lions primarily hunt large herbivores such as zebras, wildebeest, buffalo, and antelope. Working in groups, a pride’s lionesses cooperate to stalk and ambush prey. A lion can consume up to 30% of its body weight in a single meal. They are also opportunistic scavengers—often driving off smaller predators (like hyenas or wild dogs) to steal carcasses.',
    behavior: 'Lions are the most social of the big cats, living in prides that usually consist of related females, their cubs, and one or a few adult males. Females do most of the hunting, using teamwork to bring down prey. Male lions, with their larger size and mane, often take on protective roles, defending the pride’s territory (which can span over 250 km²) against rival males. Territorial behavior includes roaring choruses and scent-marking with urine. Despite their fearsome reputation, lions spend a lot of their time resting – up to 20 hours a day conserving energy for hunting bouts. When active, they are generally nocturnal or crepuscular (dawn/dusk) hunters, avoiding the heat of day.',
    status: {
      lifespan: '10-14 years in the wild',
      weight: '120-200 kg (265-440 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['siberian-tiger'],
  },
  {
    slug: 'jaguar',
    name: 'Panthera onca',
    category: 'Mammals',
    commonName: 'Jaguar',
    description: 'The largest cat of the Americas and third-largest in the world, a powerful predator of dense rainforests.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The jaguar is the largest cat of the Americas and third-largest in the world (after the tiger and lion). Stocky and immensely powerful, jaguars have muscular limbs and a broad head with a strong jaw. They boast the strongest bite force relative to size of any big cat – strong enough to crack turtle shells. Their beautiful coat is golden-yellow with black rosettes (spots with central dots) and solid black spots on limbs and head. Melanistic jaguars (all-black) are sometimes called “black panthers.” Jaguars are elusive and largely solitary, often linked with the dense tropical rainforests of the Amazon and Pantanal, but they also range in scrub, swamps, and even arid grasslands. They are exceptional swimmers and climbers, comfortable in and around water.',
    habitat: 'Jaguars historically ranged from the southwestern United States through Mexico and Central America into South America as far as northern Argentina. Today they are found mostly in the Amazon Basin, Pantanal wetlands, the Gran Chaco, and parts of Central America and Mexico (extirpated from most of the US). They inhabit tropical rainforests, flooded wetlands, dry scrub, and woodland – adaptable to various environments as long as there is dense cover and water. They often favor habitats near rivers and marshes, reflecting their propensity for swimming and hunting aquatic prey.',
    diet: 'Jaguars are apex predators with a broad diet. They are opportunistic hunters, preying on over 85 species. Common prey includes capybaras, peccaries, deer, tapirs, monkeys, birds, reptiles, and fish. Uniquely, jaguars often kill by delivering a crushing bite directly to the skull of prey, piercing the brain – a technique effective for reptiles like turtles and caimans, whose shells or thick hides are no match for the jaguar’s bite. In fact, jaguars have been observed biting through turtle and tortoise shells. They also ambush livestock in some areas, which can lead to conflict with humans. Jaguars typically drag kills to secluded spots or even up trees (though their tree-climbing is less practiced than leopards’) to eat in peace.',
    behavior: 'Jaguars are solitary and mainly nocturnal or crepuscular. Males maintain large territories that may overlap with those of several females, but they aggressively keep other adult males out. They communicate via scent marking (scrapes and urine) and deep, hoarse vocalizations (called saw-like roars). Excellent swimmers, jaguars readily enter water to catch fish, turtles, or caimans. They can be stealthy ambushers on land or lie in wait at riverbanks for prey coming to drink. Mothers give birth to 1–4 cubs and raise them without the male’s help. Cubs stay up to two years, learning to hunt before dispersing. Though formidable, jaguars yield to larger predators (like crocodilians) occasionally and avoid humans. They are a keystone species, crucial for controlling prey populations and maintaining ecosystem balance.',
    status: {
      lifespan: '12-15 years',
      weight: '70-100 kg (154-220 lbs)',
      conservation: 'Near Threatened',
    },
    relatedSpecies: ['siberian-tiger', 'cheetah'],
  },
  {
    slug: 'scarlet-macaw',
    name: 'Ara macao',
    category: 'Birds',
    commonName: 'Scarlet Macaw',
    description: 'A large, colorful parrot with a vibrant plumage of red, yellow, and blue.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The Scarlet Macaw is one of the most beautiful and iconic parrots. Its brilliant colors make it a standout in the rainforest canopy. They are highly intelligent and social birds.',
    habitat: 'They inhabit humid evergreen forests in the American tropics, from southern Mexico to Peru, Colombia, Bolivia, Venezuela and Brazil.',
    diet: 'Their diet consists mainly of fruits, nuts, and seeds. Their strong beaks are perfect for cracking open hard nuts and seeds.',
    behavior: 'Scarlet Macaws mate for life. They are often seen flying in pairs or family groups. They nest in the cavities of tall, dead trees and can be very noisy.',
    status: {
      lifespan: '40-50 years, up to 75 in captivity',
      weight: 'About 1 kg (2.2 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: ['blue-and-yellow-macaw'],
  },
  {
    slug: 'bald-eagle',
    name: 'Haliaeetus leucocephalus',
    category: 'Birds',
    commonName: 'Bald Eagle',
    description: 'The majestic national bird of the United States, known for its white head and tail.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The bald eagle is a bird of prey found in North America. A sea eagle, it has two known subspecies and forms a species pair with the white-tailed eagle. Its range includes most of Canada and Alaska, all of the contiguous United States, and northern Mexico.',
    habitat: 'They are found near large bodies of open water with an abundant food supply and old-growth trees for nesting, such as coasts, rivers, and large lakes.',
    diet: 'Their primary food is fish, which they swoop down and snatch from the water. They also eat other birds, small mammals, and carrion.',
    behavior: 'Bald eagles build some of the largest nests of any bird, often several feet across. They are monogamous and believed to mate for life. They are powerful fliers, and can reach speeds of up to 100 mph when diving.',
    status: {
      lifespan: 'About 20 years in the wild',
      weight: '3 to 6.3 kg (6.6 to 14 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: [],
    videoUrl: 'https://www.youtube.com/embed/9T-g3gGUTLw',
  },
  {
    slug: 'blue-and-yellow-macaw',
    name: 'Ara ararauna',
    category: 'Birds',
    commonName: 'Blue-and-yellow Macaw',
    description: 'A large South American parrot with blue top parts and yellow underparts.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The blue-and-yellow macaw is a large South American parrot with mostly blue top parts and light orange underparts. They are popular in aviculture because of their striking color, intelligence, and ability to mimic human speech.',
    habitat: 'It is found in woodland and tropical rainforest in South America.',
    diet: 'Their diet consists of seeds, nuts, fruits, and vegetation.',
    behavior: 'They are social birds that often form lifelong pair bonds. They are known for their loud calls and playful nature.',
    status: {
      lifespan: '30-35 years in the wild',
      weight: '0.9-1.5 kg (2-3.3 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: ['scarlet-macaw'],
  },
  {
    slug: 'emperor-penguin',
    name: 'Aptenodytes forsteri',
    category: 'Birds',
    commonName: 'Emperor Penguin',
    description: 'The tallest and heaviest of all living penguin species, endemic to Antarctica.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Emperor penguins are famed for their incredible breeding journeys. They are the only penguin species that breeds during the Antarctic winter, trekking 50-120 km (31-75 mi) over the ice to breeding colonies.',
    habitat: 'The icy coasts of Antarctica. They spend their entire lives on Antarctic ice and in its surrounding waters.',
    diet: 'Primarily fish, but also krill and squid. They can dive to depths of over 500m (1,640 ft) to find food.',
    behavior: 'Highly social animals, they form vast colonies to huddle together for warmth against the extreme cold. Males incubate a single egg for two months during the winter without eating.',
    status: {
      lifespan: '15-20 years',
      weight: '22 to 45 kg (49 to 99 lbs)',
      conservation: 'Near Threatened',
    },
    relatedSpecies: [],
  },
  {
    slug: 'komodo-dragon',
    name: 'Varanus komodoensis',
    category: 'Reptiles',
    commonName: 'Komodo Dragon',
    description: 'The world\'s largest lizard, a fearsome predator with a venomous bite.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The Komodo dragon is a species of lizard found in the Indonesian islands of Komodo, Rinca, Flores, and Gili Motang. A member of the monitor lizard family Varanidae, it is the largest living species of lizard.',
    habitat: 'They prefer hot and dry places and typically live in dry, open grassland, savanna, and tropical forest at low elevations.',
    diet: 'Komodo dragons are carnivores. They are formidable predators and will eat almost anything, including deer, pigs, smaller dragons, and even large water buffalo.',
    behavior: 'They are solitary animals, coming together only to breed and eat. They can run up to 20 kph (12 mph) in short bursts. Their bite delivers a potent mix of venom and bacteria.',
    status: {
      lifespan: 'Up to 30 years',
      weight: 'Around 70 kg (150 lbs)',
      conservation: 'Endangered',
    },
    relatedSpecies: [],
    videoUrl: 'https://www.youtube.com/embed/rGN8K-9V9UQ',
  },
  {
    slug: 'green-sea-turtle',
    name: 'Chelonia mydas',
    category: 'Reptiles',
    commonName: 'Green Sea Turtle',
    description: 'A large, migratory sea turtle named for the green color of its fat and cartilage.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The green sea turtle is a species of large sea turtle of the family Cheloniidae. It is the only species in the genus Chelonia. They are found in tropical and subtropical seas around the world.',
    habitat: 'They are primarily found in tropical and subtropical waters. They alternate between foraging grounds in shallow, coastal areas and the beaches where they were born to lay their own eggs.',
    diet: 'As adults, green sea turtles are unique among sea turtles in that they are primarily herbivores, feeding on seagrasses and algae. Juveniles are omnivores.',
    behavior: 'Green sea turtles migrate long distances between feeding grounds and nesting beaches. Females return to the same beaches where they were born to lay their eggs.',
    status: {
      lifespan: '80 years or more',
      weight: 'Up to 190 kg (420 lbs)',
      conservation: 'Endangered',
    },
    relatedSpecies: ['leatherback-sea-turtle'],
  },
  {
    slug: 'leatherback-sea-turtle',
    name: 'Dermochelys coriacea',
    category: 'Reptiles',
    commonName: 'Leatherback Sea Turtle',
    description: 'The largest of all living turtles and is the fourth-heaviest modern reptile.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The leatherback sea turtle, sometimes called the lute turtle or leathery turtle, is the largest of all living turtles. It can easily be differentiated from other modern sea turtles by its lack of a bony shell, hence the name. Instead, its carapace is covered by skin and oily flesh.',
    habitat: 'They are found in the open ocean and have the widest distribution of any sea turtle, ranging from the tropics to sub-polar regions.',
    diet: 'Their diet consists almost entirely of jellyfish and other soft-bodied invertebrates.',
    behavior: 'They are the most migratory of all sea turtle species, undertaking long-distance migrations between feeding and nesting grounds.',
    status: {
      lifespan: 'Around 30 years in the wild',
      weight: '250 to 700 kg (550 to 1,540 lb)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['green-sea-turtle'],
  },
  {
    slug: 'saltwater-crocodile',
    name: 'Crocodylus porosus',
    category: 'Reptiles',
    commonName: 'Saltwater Crocodile',
    description: 'The largest living reptile and crocodilian known to mankind.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The saltwater crocodile is a formidable and opportunistic hypercarnivorous apex predator. They are known for their immense size and aggressive nature.',
    habitat: 'They inhabit brackish and freshwater habitats from eastern India, Southeast Asia, and northern Australia.',
    diet: 'They consume a wide range of prey, including fish, mammals, and birds. They are ambush predators, waiting for potential prey to get close before launching a swift and powerful attack.',
    behavior: 'Saltwater crocodiles are highly territorial. They communicate through a variety of vocalizations and are most active in the warmer months.',
    status: {
      lifespan: 'Up to 70 years',
      weight: 'Up to 1,000 kg (2,200 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: [],
  },
  {
    slug: 'clownfish',
    name: 'Amphiprioninae',
    category: 'Marine Life',
    commonName: 'Clownfish',
    description: 'A small, brightly colored fish famous for its symbiotic relationship with sea anemones.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Clownfish, or anemonefish, are small fish found in warmer waters of the Indian and Pacific oceans. They are known for their striking orange and white patterns. There are about 30 recognized species.',
    habitat: 'They form a symbiotic relationship with sea anemones. The clownfish is protected from the anemone\'s stinging cells by a layer of mucus, and in turn, the clownfish defends the anemone from predators.',
    diet: 'Clownfish are omnivores. They eat a variety of small invertebrates and algae, as well as undigested food from their host anemones.',
    behavior: 'Clownfish live in a strict hierarchy within a single anemone. The largest and most aggressive female is at the top. All clownfish are born male; they have the ability to change sex to become the dominant female if the previous one dies.',
    status: {
      lifespan: '6-10 years',
      weight: 'Up to 250 grams',
      conservation: 'Not evaluated for most species, but threatened by reef degradation.',
    },
    relatedSpecies: ['orca'],
  },
  {
    slug: 'great-white-shark',
    name: 'Carcharodon carcharias',
    category: 'Marine Life',
    commonName: 'Great White Shark',
    description: 'One of the ocean\'s most powerful predators, known for its size and serrated teeth.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'The great white shark is a species of large mackerel shark which can be found in the coastal surface waters of all the major oceans. It is notable for its size, with mature female individuals growing up to 6.1 m (20 ft) in length.',
    habitat: 'They are found in cool, coastal waters throughout the world. They have been recorded at depths as great as 1,200 m (3,900 ft).',
    diet: 'Young great whites eat fish, rays, and other sharks. Adults feed on larger prey, including pinnipeds (like sea lions and seals), small-toothed whales (like dolphins), and sea turtles.',
    behavior: 'Great whites are solitary and highly migratory, with some individuals making trans-oceanic journeys. They are apex predators, with only orcas known to prey on them.',
    status: {
      lifespan: 'Estimated 70 years or more',
      weight: 'Up to 2,268 kg (5,000 lbs)',
      conservation: 'Vulnerable',
    },
    relatedSpecies: ['orca'],
  },
  {
    slug: 'orca',
    name: 'Orcinus orca',
    category: 'Marine Life',
    commonName: 'Orca (Killer Whale)',
    description: 'A toothed whale belonging to the oceanic dolphin family, of which it is the largest member.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Orcas, or killer whales, are apex predators found in all of the world\'s oceans. They are known for their complex social structures, hunting techniques, and vocal behaviors.',
    habitat: 'They are found in a variety of marine environments, from Arctic and Antarctic regions to tropical seas.',
    diet: 'Their diet is diverse and includes fish, seals, sea lions, dolphins, and even large whales.',
    behavior: 'Orcas are highly social and live in family groups called pods. They communicate with a wide range of clicks, whistles, and pulsed calls.',
    status: {
      lifespan: '50-90 years',
      weight: 'Up to 5,400 kg (12,000 lbs)',
      conservation: 'Data Deficient',
    },
    relatedSpecies: ['great-white-shark', 'clownfish'],
  },
  {
    slug: 'bottlenose-dolphin',
    name: 'Tursiops truncatus',
    category: 'Marine Life',
    commonName: 'Bottlenose Dolphin',
    description: 'A well-known species of dolphin recognized for its intelligence and charisma.',
    imageUrl: 'https://placehold.co/400x300.png',
    bannerUrl: 'https://placehold.co/1200x400.png',
    overview: 'Bottlenose dolphins are highly intelligent marine mammals known for their playful behavior and complex social lives. Their curved mouths give the appearance of a friendly, permanent smile.',
    habitat: 'Found in temperate and tropical waters worldwide, inhabiting both coastal and deep-water environments.',
    diet: 'They are skilled hunters, feeding on a varied diet of fish, squid, and crustaceans. They often hunt cooperatively.',
    behavior: 'They live in social groups called pods and communicate using a complex system of squeaks, whistles, and body language. They are known for their acrobatic leaps out of the water.',
    status: {
      lifespan: '40-60 years',
      weight: '150 to 650 kg (330 to 1,430 lbs)',
      conservation: 'Least Concern',
    },
    relatedSpecies: ['orca'],
  },
];

export const categories = ['Mammals', 'Birds', 'Reptiles', 'Marine Life'];

export const getAnimalBySlug = (slug: string) => animals.find(a => a.slug === slug);
export const getAnimalsByCategory = (category: string) => animals.filter(a => a.category === category);
